### ISSUE TITLE
uninitialized constant Spree::SalesConfiguration::Config

### ISSUE THREAD

**Issue by restot** [ronzalo/spree_sales#29] opened 2019-02-17 13:08 UTC
Showing /home/vm/.rvm/gems/ruby-2.5.1@spree370/bundler/gems/spree_sales-db75d015eb84/app/views/spree/admin/sale_prices/_form.html.erb where line #12 raised:

uninitialized constant Spree::SalesConfiguration::Config

Extracted source (around line #76):
74            # If the constant was actually loaded, something else went wrong?
75            raise if from_mod.const_defined?(const_name)
76            CoreExt::ActiveSupport.without_bootsnap_cache { super }
77         end
78
79          # Signature has changed a few times over the years; easiest to not

Trace of template inclusion: /home/vm/.rvm/gems/ruby-2.5.1@spree370/bundler/gems/spree_sales-db75d015eb84/app/views/spree/admin/sale_prices/index.html.erb

Spree v3.7.0 How can i fix it?

**Comment by ronzalo** [comment] 2019-02-18 04:13
Try updating the gem to the last version, but if that doesn't works, decorate the base_helper#calculators method to something like this
```ruby
def sale_calculators
  calculators = [Spree::Calculator::AmountSalePriceCalculator, Spree::Calculator::PercentOffSalePriceCalculator].map do |calculator|
    [calculator.title, calculator.name]
  end

  options_for_select(calculators)
end
```
https://github.com/ronzalo/spree_sales/blob/master/app/helpers/spree/base_helper_decorator.rb#L35

**Comment by gbriyad** [comment] 2020-08-13 14:49
I'm having a similar kind of problem but only in the Production environment. In my case, the Sale Calculator array is empty . I tried to figure out what was causing the problem. It seems that in **engine.rb** file, these array appends are not working correctly.

`SpreeSales::Config = Spree::SalesConfiguration.new`
`SpreeSales::Config[:sale_calculators] << Spree::Calculator::AmountSalePriceCalculator.to_s`
`SpreeSales::Config[:sale_calculators] << Spree::Calculator::PercentOffSalePriceCalculator.to_s`

I made the **config.cache_classes = false** in my **production.rb** file and it worked. So, the problem is with caching.
Im currently decorating the base_helper#calculators as @ronzalo said as a workaround.

But is there any way to stick with Engine initializer with cache_class=true to solve this problem?
[Spree 4.1, Rails 6]

**Comment by gbriyad** [comment] 2020-08-13 15:05
I'm having a similar kind of problem but only in the **Production** environment. In my case, the **SpreeSales::Config[:sale_calculators]** array is empty . I tried to figure out what was causing the problem. It seems that in **engine.rb** file, these array appends are not working correctly.

`SpreeSales::Config = Spree::SalesConfiguration.new`
`SpreeSales::Config[:sale_calculators] << Spree::Calculator::AmountSalePriceCalculator.to_s`
`SpreeSales::Config[:sale_calculators] << Spree::Calculator::PercentOffSalePriceCalculator.to_s`

I made the **config.cache_classes = false** in my **production.rb** file and it worked. So, the problem is with caching.
Im currently decorating the base_helper#calculators as @ronzalo said as a workaround.

But is there any way to stick with Engine initializer with cache_class=true to solve this problem?
[Spree 4.1, Rails 6]

**Comment by twnaing** [comment] 2020-08-31 20:13
Event with `config.cache_classes = false`, I cannot get the calculators.

Spree: 4.1.5
Spree_sales: 4.0.0 (4-0-stable) 70360a1a4de0
Rails: 6.0.2.2

Change 

https://github.com/ronzalo/spree_sales/blob/70360a1a4de095ddec19eb4b457e1da9196ef00a/lib/spree_sales/engine.rb#L17-L18

to

```ruby
SpreeSales::Config[:sale_calculators] = [Spree::Calculator::AmountSalePriceCalculator.to_s, Spree::Calculator::PercentOffSalePriceCalculator.to_s]
```

fix the issue for me (with `cache_classes=true`).

Before someone updates the code, maybe the best way is to override `_form.html.erb` and replace `sale_calculators` with the array. (The code hasn't been tried yet).

https://github.com/ronzalo/spree_sales/blob/70360a1a4de095ddec19eb4b457e1da9196ef00a/app/views/spree/admin/sale_prices/_form.html.erb#L12

```ruby
          <%= f.select :calculator, options_from_collection_for_select([Spree::Calculator::AmountSalePriceCalculator,Spree::Calculator::PercentOffSalePriceCalculator], :name, :title), {}, {:class => 'select2'} %>
```

**Comment by ronzalo** [comment] 2020-09-01 16:42
@twnaing fixed on branch 4-0-stable

**Closed by ronzalo** 2020-09-01 16:42 UTC
